# Generated by Django 5.0.3 on 2024-03-24 03:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_fee_category_sclass_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fees_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fees Amount')),
                ('partial_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Partial Payment')),
                ('voucher_id', models.CharField(max_length=100, verbose_name='Voucher ID')),
                ('fees_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.fee_category', verbose_name='Fees Category')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fees',
            },
        ),
    ]
