# Generated by Django 5.0.3 on 2024-03-24 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fee Amount')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('class_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.sclass', verbose_name='Class Category')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.fee_category', verbose_name='Fee Category')),
            ],
            options={
                'verbose_name': 'Fee Set',
                'verbose_name_plural': 'Fee Sets',
            },
        ),
    ]
