# Generated by Django 5.0.3 on 2024-03-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_alter_fee_fees_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fees_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fees Amount'),
        ),
    ]
