# Generated by Django 5.0.3 on 2024-03-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_alter_fee_fees_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeset',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
